# tasks file for 6520
- name: resoconto in file {{ logfile }}
  shell: echo "Applicato il bug {{bug}} dall'utente $USER in data $(date +%d-%m-%Y_%H:%M:%S) sui server {{inventory_hostname}} " >> {{ logfile }}
  delegate_to: localhost
  changed_when: false
- name: resoconto in database ansible
  shell: mysql --user=ansible_update --password=$(cat /home/password_insert) -e "insert into ansible.bugs values ( '{{bug}}','$USER','$(date +%d-%m-%Y_%H:%M:%S)','{{inventory_hostname}}');"
  delegate_to: localhost
  changed_when: false

- name: Controlla se è un server su cui sta girando glassfish
  shell: ps -ef | grep  java | grep glassfish 
  check_mode: false
  failed_when: false
  changed_when: false
  register: glassfish_up_6520

- name: Controlla se è deployato agentDesktopMGR
  shell: /opt/glassfish/bin/asadmin list-applications | grep agentdesktopmanager | awk '{print $1}'
  environment:
        PATH: "{{ ansible_env.PATH }}:/usr/java/default/bin" 
  check_mode: false
  failed_when: false
  changed_when: false
  when: glassfish_up_6520.rc == 0
  register: manager_presente_6520

- name: Aggiorna AgentDesktopMGR
  include: aggiorna_agentdesktopmgr.yml
  when:
  - glassfish_up_6520.rc == 0
  - manager_presente_6520.rc == 0
  
  
